### ISSUE TITLE
Simulated switch's status change is not noticed after a day

### ISSUE THREAD

**Issue by LxonWWW** [Samsung/SamsungAutomationStudio#51]
Hi!

I have some nodes in [SASM ](https://sasm.developer.samsung.com/#nodes) where I check the status of a simulated switch.
Everything works fine for about a day. After that, changes to the status of the simulated switch will not be noticed by SASM, but the node is still running. When I stop and re-deploy the node it will work again for about a day.

My Setup looks like this:

![Screenshot 2022-03-31 at 18-26-03 Samsung Automation Studio](https://user-images.githubusercontent.com/29819445/161104206-881a2240-31d7-4db2-93a7-9c54091033ec.png)

Greetings,
Leon Dierkes

**Comment by dplaya-min** [comment]
Hi. Leon. 
I think there is a problem with the SSE connection. 
SSE has not been released to open nodes because there are not enough tests for ST server connection. It's outside of SASM.
SASM should automatically renew the SSE connection. We have to see if there are any changes to those rules.
We need time to check due to the change of contact person.
thank you.

**Comment by hojoon22-lee** [comment]
Hi Leon,

This issue has been resolved. Please verify the SSE node is working.

Thank you for your interest in Samsung Automation Studio.

**Comment by LxonWWW** [comment]
Verified that the issue is fixed.
